In [1]:
import torch
import torch.nn as nn

## Sequential Model

In [76]:
X = torch.randn((10, 20)) # Batch of 10 elements with 20 features

In [7]:
sequential_model = nn.Sequential(
    nn.Linear(20, 64),
    nn.ReLU(),
    nn.Linear(64, 32),
    nn.ReLU(),
    nn.Linear(32, 5)
)

print (sequential_model)

Sequential(
  (0): Linear(in_features=20, out_features=64, bias=True)
  (1): ReLU()
  (2): Linear(in_features=64, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=5, bias=True)
)


In [8]:
y_pred_1 = sequential_model(X)

print (y_pred_1)

## Functional Model

In [77]:
X = torch.randn((10, 20)) # Batch of 10 elements with 20 features

In [78]:
class FunctionalModel(nn.Module):
  def __init__(self):
    super(FunctionalModel, self).__init__()
    self.linear1 = nn.Linear(20, 64)
    self.linear2 = nn.Linear(64, 32)
    self.linear3 = nn.Linear(32, 5)
    self.relu = nn.ReLU()
  def forward(self, X):
    x = self.linear1(X)
    x = self.relu(x)
    x = self.linear2(x)
    x = self.relu(x)
    x = self.linear3(x)
    return x

In [79]:
functional_model = FunctionalModel()

print (functional_model)

FunctionalModel(
  (linear1): Linear(in_features=20, out_features=64, bias=True)
  (linear2): Linear(in_features=64, out_features=32, bias=True)
  (linear3): Linear(in_features=32, out_features=5, bias=True)
  (relu): ReLU()
)


In [80]:
y_pred_2 = functional_model(X)

print (y_pred_2)

tensor([[-0.0913, -0.0280,  0.1992,  0.1007, -0.0734],
        [-0.0701, -0.0778,  0.1788,  0.0422, -0.1036],
        [-0.0977, -0.1770,  0.2507, -0.0224, -0.2034],
        [-0.0700, -0.0633,  0.1873, -0.0439, -0.1384],
        [ 0.0675, -0.1063,  0.1793,  0.0881, -0.1717],
        [-0.0090,  0.0302,  0.2752,  0.1955, -0.0887],
        [ 0.0062, -0.1213,  0.1738,  0.2593, -0.0870],
        [-0.0068, -0.0931,  0.1267,  0.1528, -0.0729],
        [-0.0550, -0.1319,  0.2003,  0.1094, -0.0941],
        [-0.0423, -0.0977,  0.2114,  0.1206, -0.0725]],
       grad_fn=<AddmmBackward0>)


## Simple Linear Regression Model

In [101]:
X = torch.tensor([[1.0], [2.0], [3.0], [4.0], [5.0]])
y = torch.tensor([[2.0], [4.0], [6.0], [8.0], [10.0]])

In [102]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super(LinearRegressionModel, self).__init__()
    self.linear = nn.Linear(in_features=1, out_features=1)
  def forward(self, X):
    x = self.linear(X)
    return x

In [103]:
linear_regression_model = LinearRegressionModel()

print (linear_regression_model)

LinearRegressionModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)


In [104]:
criterion = nn.MSELoss()

optimizer = torch.optim.SGD(linear_regression_model.parameters(), lr=0.011)

In [105]:
num_epochs = 25

for epoch in range(num_epochs):
    # Forward pass: Compute predicted y
    y_pred = linear_regression_model(X)

    # Compute loss
    loss = criterion(y_pred, y)

    # Zero gradients
    optimizer.zero_grad()

    # Backward pass: Compute gradients
    loss.backward()

    # Update parameters
    optimizer.step()

    # Print progress
    print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

Epoch [1/25], Loss: 51.1010
Epoch [2/25], Loss: 28.0650
Epoch [3/25], Loss: 15.4593
Epoch [4/25], Loss: 8.5609
Epoch [5/25], Loss: 4.7854
Epoch [6/25], Loss: 2.7188
Epoch [7/25], Loss: 1.5873
Epoch [8/25], Loss: 0.9673
Epoch [9/25], Loss: 0.6274
Epoch [10/25], Loss: 0.4407
Epoch [11/25], Loss: 0.3378
Epoch [12/25], Loss: 0.2807
Epoch [13/25], Loss: 0.2488
Epoch [14/25], Loss: 0.2306
Epoch [15/25], Loss: 0.2200
Epoch [16/25], Loss: 0.2135
Epoch [17/25], Loss: 0.2092
Epoch [18/25], Loss: 0.2062
Epoch [19/25], Loss: 0.2039
Epoch [20/25], Loss: 0.2019
Epoch [21/25], Loss: 0.2002
Epoch [22/25], Loss: 0.1986
Epoch [23/25], Loss: 0.1970
Epoch [24/25], Loss: 0.1955
Epoch [25/25], Loss: 0.1940


In [106]:
print (y_pred)

tensor([[2.7446],
        [4.4572],
        [6.1698],
        [7.8824],
        [9.5950]], grad_fn=<AddmmBackward0>)


## Simple Multi Class Classification Model

In [218]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [219]:
if torch.cuda.is_available():
  print ("GPU")
else:
  print ("CPU")

GPU


In [220]:
device = torch.device("cuda" if torch.cuda.is_available() else "cuda")

print (device)

cuda


In [221]:
iris = load_iris()

X = iris.data
y = iris.target

In [222]:
print (iris.feature_names)
print (iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [223]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [224]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [225]:
X_train = torch.tensor(X_train, dtype=torch.float32).to(device)
X_test = torch.tensor(X_test, dtype=torch.float32).to(device)
y_train = torch.tensor(y_train, dtype=torch.long).to(device)
y_test = torch.tensor(y_test, dtype=torch.long).to(device)

In [226]:
print (X_train.shape)
print (X_test.shape)

torch.Size([120, 4])
torch.Size([30, 4])


In [237]:
class NeuralNet(nn.Module):
  def __init__(self, input_size, hidden_size, num_classes):
    super(NeuralNet, self).__init__()
    self.fc1 = nn.Linear(input_size, hidden_size)
    self.fc2 = nn.Linear(hidden_size, num_classes)
    self.relu = nn.ReLU()
  def forward(self, X):
    x = self.relu(self.fc1(X))
    x = self.fc2(x)
    # x = F.softmax(x, dim=1)
    return x

In [238]:
input_size = X_train.shape[1]
hidden_size = 100
num_classes = len(iris.target_names)

print (input_size)
print (hidden_size)
print (num_classes)

4
100
3


In [239]:
neuralNet = NeuralNet(input_size, hidden_size, num_classes).to(device)

print (neuralNet)

NeuralNet(
  (fc1): Linear(in_features=4, out_features=100, bias=True)
  (fc2): Linear(in_features=100, out_features=3, bias=True)
  (relu): ReLU()
)


In [240]:
num_epochs = 100

In [244]:
def train_model(X_train, y_train):
  criterion = nn.CrossEntropyLoss() # NLLLS(Negative Log Likelihood Loss) + LogSoftmax
  optimizer = optim.Adam(neuralNet.parameters(), lr=0.01)

  for epoch in range(num_epochs):
    y_pred = neuralNet(X_train)
    loss = criterion(y_pred, y_train)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(f'Epoch [{epoch + 1}/{num_epochs}], Loss: {loss.item():.4f}')

In [245]:
train_model(X_train, y_train)

Epoch [1/100], Loss: 0.0416
Epoch [2/100], Loss: 0.0411
Epoch [3/100], Loss: 0.0471
Epoch [4/100], Loss: 0.0402
Epoch [5/100], Loss: 0.0453
Epoch [6/100], Loss: 0.0420
Epoch [7/100], Loss: 0.0393
Epoch [8/100], Loss: 0.0412
Epoch [9/100], Loss: 0.0419
Epoch [10/100], Loss: 0.0399
Epoch [11/100], Loss: 0.0383
Epoch [12/100], Loss: 0.0390
Epoch [13/100], Loss: 0.0397
Epoch [14/100], Loss: 0.0387
Epoch [15/100], Loss: 0.0375
Epoch [16/100], Loss: 0.0376
Epoch [17/100], Loss: 0.0379
Epoch [18/100], Loss: 0.0375
Epoch [19/100], Loss: 0.0365
Epoch [20/100], Loss: 0.0360
Epoch [21/100], Loss: 0.0362
Epoch [22/100], Loss: 0.0361
Epoch [23/100], Loss: 0.0354
Epoch [24/100], Loss: 0.0349
Epoch [25/100], Loss: 0.0347
Epoch [26/100], Loss: 0.0346
Epoch [27/100], Loss: 0.0342
Epoch [28/100], Loss: 0.0337
Epoch [29/100], Loss: 0.0334
Epoch [30/100], Loss: 0.0332
Epoch [31/100], Loss: 0.0328
Epoch [32/100], Loss: 0.0323
Epoch [33/100], Loss: 0.0319
Epoch [34/100], Loss: 0.0316
Epoch [35/100], Loss: 0

In [246]:
neuralNet(X_train)

tensor([[ 25.8434,   2.5820, -55.8101],
        [ 22.5470,   9.1378, -58.2652],
        [ -9.1717,   8.0957,  -5.3276],
        [ 21.3624,   3.5399, -48.2940],
        [ 22.1253,   0.3682, -47.3386],
        [-19.2779,   1.4254,   6.8286],
        [ -8.0532,   7.0170,  -4.6766],
        [ 20.8000,   5.6056, -49.1656],
        [ 22.8976,   4.5687, -51.9389],
        [ 26.1414,   6.5061, -60.6684],
        [-15.8204,   0.2614,   6.7572],
        [ -5.1893,   7.9983,  -7.3784],
        [-11.0058,   5.9011,  -2.6429],
        [ 21.7225,   6.3951, -51.9298],
        [ 21.5406,   6.7782, -51.6125],
        [ -7.7012,   8.6474,  -6.5597],
        [-13.7116,   2.1314,   3.3103],
        [-14.4000,  -0.3443,   4.7811],
        [ -9.6326,   7.7705,  -4.3456],
        [-20.2223,  -4.9219,   8.3879],
        [ -6.5874,   8.1039,  -5.0662],
        [-25.9505,  -5.2752,  11.1876],
        [ -6.9795,   6.7322,  -3.4283],
        [ 21.6143,   5.0187, -50.0367],
        [-28.0979,  -5.3932,  12.1758],
